#! /bin/bash
set -e

if (git ls-files --others --exclude-standard | grep .) then echo "untracked files"; exit 1; fi

cargo check
cargo check --target=wasm32-unknown-unknown

echo -n TODOs\:
echo $(( $(git grep TODO | wc -l) -2 ))